### ISSUE TITLE
I can't run the docker image

### ISSUE THREAD

**Issue by NotSoSeriouss** [Infinify/InfiniteWhiteboard#23]
I managed to build a docker image from the repo(but I had to change  the node version from the DockerFile because it was too old) but I'm not able to run it correctly:
Every time I get the same error from mongo db stating that it couldn't establish a connection.
I really don't know what to do, and I already looked evereywhere and tried everything.
Here's the latest log from Docker:

```
2022-12-24 13:58:06 Debugger listening on ws://0.0.0.0:9229/44ade2af-d0c8-4e1d-832c-a9f950a1fb41
2022-12-24 13:58:06 For help, see: https://nodejs.org/en/docs/inspector
2022-12-24 13:58:28 Error [MongoError]: failed to connect to server [iwb-mongodb:27017] on first connect [Error: connect ECONNREFUSED 35.152.66.6:27017
2022-12-24 13:58:28     at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1141:16) {
2022-12-24 13:58:28   name: 'MongoError',
2022-12-24 13:58:28   message: 'connect ECONNREFUSED 35.152.66.6:27017'
2022-12-24 13:58:28 }]
2022-12-24 13:58:28     at Pool.<anonymous> (/app/node_modules/mongodb-core/lib/topologies/server.js:336:35)
2022-12-24 13:58:28     at Pool.emit (events.js:315:20)
2022-12-24 13:58:28     at Connection.<anonymous> (/app/node_modules/mongodb-core/lib/connection/pool.js:280:12)
2022-12-24 13:58:28     at Object.onceWrapper (events.js:422:26)
2022-12-24 13:58:28     at Connection.emit (events.js:315:20)
2022-12-24 13:58:28     at Socket.<anonymous> (/app/node_modules/mongodb-core/lib/connection/connection.js:189:49)
2022-12-24 13:58:28     at Object.onceWrapper (events.js:422:26)
2022-12-24 13:58:28     at Socket.emit (events.js:315:20)
2022-12-24 13:58:28     at emitErrorNT (internal/streams/destroy.js:84:8)
2022-12-24 13:58:28     at processTicksAndRejections (internal/process/task_queues.js:84:21) {
2022-12-24 13:58:28   name: 'MongoError',
2022-12-24 13:58:28   message: 'failed to connect to server [iwb-mongodb:27017] on first connect [Error: connect ECONNREFUSED 35.152.66.6:27017\n' +
2022-12-24 13:58:28     '    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1141:16) {\n' +
2022-12-24 13:58:28     "  name: 'MongoError',\n" +
2022-12-24 13:58:28     "  message: 'connect ECONNREFUSED 35.152.66.6:27017'\n" +
2022-12-24 13:58:28     '}]'
2022-12-24 13:58:28 }
2022-12-24 13:58:28 Error [MongoError]: failed to connect to server [iwb-mongodb:27017] on first connect [Error: connect ECONNREFUSED 35.152.66.6:27017
2022-12-24 13:58:28     at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1141:16) {
2022-12-24 13:58:28   name: 'MongoError',
2022-12-24 13:58:28   message: 'connect ECONNREFUSED 35.152.66.6:27017'
2022-12-24 13:58:28 }]
2022-12-24 13:58:28     at Pool.<anonymous> (/app/node_modules/mongodb-core/lib/topologies/server.js:336:35)
2022-12-24 13:58:28     at Pool.emit (events.js:315:20)
2022-12-24 13:58:28     at Connection.<anonymous> (/app/node_modules/mongodb-core/lib/connection/pool.js:280:12)
2022-12-24 13:58:28     at Object.onceWrapper (events.js:422:26)
2022-12-24 13:58:28     at Connection.emit (events.js:315:20)
2022-12-24 13:58:28     at Socket.<anonymous> (/app/node_modules/mongodb-core/lib/connection/connection.js:189:49)
2022-12-24 13:58:28     at Object.onceWrapper (events.js:422:26)
2022-12-24 13:58:28     at Socket.emit (events.js:315:20)
2022-12-24 13:58:28     at emitErrorNT (internal/streams/destroy.js:84:8)
2022-12-24 13:58:28     at processTicksAndRejections (internal/process/task_queues.js:84:21) {
2022-12-24 13:58:28   name: 'MongoError',
2022-12-24 13:58:28   message: 'failed to connect to server [iwb-mongodb:27017] on first connect [Error: connect ECONNREFUSED 35.152.66.6:27017\n' +
2022-12-24 13:58:28     '    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1141:16) {\n' +
2022-12-24 13:58:28     "  name: 'MongoError',\n" +
2022-12-24 13:58:28     "  message: 'connect ECONNREFUSED 35.152.66.6:27017'\n" +
2022-12-24 13:58:28     '}]'
2022-12-24 13:58:28 }

```

**Comment by msand** [comment]
@NotSoSeriouss Can you try with the latest commit from master?
